### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Motzee** [Motzee/nicomak#1]
- [x] initialiser un projet Symfony et le pousser sur git
- [x] identifier les attentes prioritaires du projet : BBD à deux entités (User [id, firstname, lastname, role, passwd, salt, avatar] et Thanks [id, fromwho, towho, reason, datethanks]) donc session utilisateur et utilisation des forms.
- [x] configuration parameters.yml
- [ ] création user mysql et bdd
- [x] ajout FosUserBundle
- [x] création entité Thanks
- [x] génération des tables depuis les entités
- [x] génération d'un CRUD avec formulaire d'entités pour Thanks

Restant :
- [ ] jointures de tables
- [ ] restreinte formulaire d'inscription
- [ ] ajout champs formulaire d'inscription
- [ ] retrait privilèges accès db à faute de frappe db_nocomak
